// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.22.2
// source: proto/reverser/reverser.proto

package reverser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReverserService_Reverse_FullMethodName = "/reverser.ReverserService/Reverse"
)

// ReverserServiceClient is the client API for ReverserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverserServiceClient interface {
	Reverse(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*ReverseResponse, error)
}

type reverserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReverserServiceClient(cc grpc.ClientConnInterface) ReverserServiceClient {
	return &reverserServiceClient{cc}
}

func (c *reverserServiceClient) Reverse(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*ReverseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseResponse)
	err := c.cc.Invoke(ctx, ReverserService_Reverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverserServiceServer is the server API for ReverserService service.
// All implementations must embed UnimplementedReverserServiceServer
// for forward compatibility.
type ReverserServiceServer interface {
	Reverse(context.Context, *ReverseRequest) (*ReverseResponse, error)
	mustEmbedUnimplementedReverserServiceServer()
}

// UnimplementedReverserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReverserServiceServer struct{}

func (UnimplementedReverserServiceServer) Reverse(context.Context, *ReverseRequest) (*ReverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reverse not implemented")
}
func (UnimplementedReverserServiceServer) mustEmbedUnimplementedReverserServiceServer() {}
func (UnimplementedReverserServiceServer) testEmbeddedByValue()                         {}

// UnsafeReverserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverserServiceServer will
// result in compilation errors.
type UnsafeReverserServiceServer interface {
	mustEmbedUnimplementedReverserServiceServer()
}

func RegisterReverserServiceServer(s grpc.ServiceRegistrar, srv ReverserServiceServer) {
	// If the following call pancis, it indicates UnimplementedReverserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReverserService_ServiceDesc, srv)
}

func _ReverserService_Reverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverserServiceServer).Reverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverserService_Reverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverserServiceServer).Reverse(ctx, req.(*ReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReverserService_ServiceDesc is the grpc.ServiceDesc for ReverserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reverser.ReverserService",
	HandlerType: (*ReverserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reverse",
			Handler:    _ReverserService_Reverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reverser/reverser.proto",
}
